services:
  sample-saas-db:
    image: postgres:12.4
    ports:
      - 5432
    volumes:
      - type: volume
        source: samplesaas-postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  sample-saas:
    image: node:16.14.0
    ports:
      - 3030:3000
    volumes:
      - .:/app
      - ./root:/root
    env_file:
      - .env
    environment:
      - PGHOST=sample-saas-db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      # - NODE_TLS_REJECT_UNAUTHORIZED=0
      - BUNNY_SCOPE="standard:read standard:write product:read product:write security:read security:write"
    command: bash -c "cd /app && npm install && npm run dev"
volumes:
  samplesaas-postgres:
