services:
  postgres:
    image: postgres:12.4
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: samplesaas-postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  sample-saas:
    image: node:16.14.0
    ports:
      - 3030:3000
    volumes:
      - .:/app
      - ./root:/root
    env_file:
      - .env
    command: bash -c "cd /app && npm install && npm start"
volumes:
  samplesaas-postgres:
